# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cdbartSigmaFix_inf <- function(n, p, np, ixv, iyv, ixpv, SigmaInv, m, numcutv, nd, burn, mybeta, alpha, tau, dart, theta, omega, a, b, rho, aug, nkeeptrain, nkeeptest, nkeeptestme, nkeeptreedraws, printevery, showMessage) {
    .Call(`_CbartGP_cdbartSigmaFix_inf`, n, p, np, ixv, iyv, ixpv, SigmaInv, m, numcutv, nd, burn, mybeta, alpha, tau, dart, theta, omega, a, b, rho, aug, nkeeptrain, nkeeptest, nkeeptestme, nkeeptreedraws, printevery, showMessage)
}

wbart_inf <- function(n, p, np, ixv, iyv, ixpv, m, numcutv, nd, burn, mybeta, alpha, tau, nu, lambda, sigma, iwv, dart, theta, omega, grpv, a, b, rho, aug, nkeeptrain, nkeeptest, nkeeptestme, nkeeptreedraws, printevery, xifo, showMessage) {
    .Call(`_CbartGP_wbart_inf`, n, p, np, ixv, iyv, ixpv, m, numcutv, nd, burn, mybeta, alpha, tau, nu, lambda, sigma, iwv, dart, theta, omega, grpv, a, b, rho, aug, nkeeptrain, nkeeptest, nkeeptestme, nkeeptreedraws, printevery, xifo, showMessage)
}

